import path from 'path';

import fs from 'fs-extra';
import { merge } from 'lodash-es';

import { AdditionalFeatureType } from '../types';

import type { GenerateTask } from '../types';

const common = {
  version: '0.0.1',
  description: 'A project generated by July CLI',
  type: 'module',
  exports: {
    '.': { import: './dist/index.js', types: './dist/index.d.ts' },
  },
  main: 'dist/index.js',
  types: 'dist/index.d.ts',
  module: 'dist/index.js',
  private: false,
  publishConfig: {
    access: 'public',
  },
  repository: {},
  scripts: {
    dev: 'vite',
    build: 'vite build',
  },
  files: ['dist', 'package.json'],
  keywords: [],
  author: '',
  license: 'ISC',
  devDependencies: {
    typescript: '^5.9.3',
    vite: '^8.0.0',
    'vite-plugin-dts': '^4.5.4',
  },
};

const eslint = {
  devDependencies: {
    '@july_cm/eslint-config': '^2.4.2',
    eslint: '^9.39.4',
  },
};

export const generatePackageJsonTask: GenerateTask = async (config) => {
  const filePath = path.resolve(config.projectDir, 'package.json');
  if (fs.existsSync(filePath)) {
    return;
  }
  const configs: any = [common];
  if (config.features[AdditionalFeatureType.ESLintConfig]) {
    configs.push(eslint);
  }

  const content = merge({ name: config.packageName }, ...configs);
  await fs.writeJson(filePath, content, { spaces: 2 });
};
