

import fs from 'fs-extra';
import path from 'path';
import { Config } from './types';

export const generatePackageJson = async (config: Config) => {

  const packageJson = {
    name: config.packageName,
    version: '1.0.0',
    description: 'A project generated by July CLI',
    main: 'index.js',
    scripts: {
      test: 'echo \"Error: no test specified\" && exit 1',
    },
    keywords: [],
    author: '',
    license: 'ISC',
    devDependencies: {
      "@july_cm/eslint-config": "^2.4.2",
      "eslint": "^10.0.2",
      "typescript": "^5.9.3",
    }
  }
  await fs.writeJson(path.resolve(config.projectDir, 'package.json'), packageJson, { spaces: 2 });
}
