name: Release

permissions:
  contents: write
  id-token: write

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version type (e.g. patch, minor, major, auto)'
        required: false
        type: choice
        options:
          - patch
          - minor
          - major
          - auto
        default: auto

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: pnpm add -g release-it @release-it/conventional-changelog

      - name: Release it
        run: |
          if [ "${{ github.event.inputs.version_type }}" = "auto" ]; then
            release-it --ci --npm.skipChecks\
              --plugins.@release-it/conventional-changelog
          else
            release-it --ci  --npm.skipChecks\
              --plugins.@release-it/conventional-changelog.ignoreRecommendedBump\
              ${{ github.event.inputs.version_type }}
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true